CREATE TABLE TOWN (
    ID LONG AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CAR (
    ID LONG AUTO_INCREMENT NOT NULL,
    LABEL VARCHAR(100) NOT NULL,
    CLEAN BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PERSON_ADDRESS (
    ID LONG AUTO_INCREMENT NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    ID_TOWN LONG NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON_ADDRESS_TOWN FOREIGN KEY (ID_TOWN) REFERENCES TOWN (ID)
);

CREATE TABLE PERSON (
    ID LONG AUTO_INCREMENT NOT NULL,
    FIRSTNAME VARCHAR(40) NULL,
    AGE INT NULL,
    BIRTHDAY BOOLEAN NULL,
    ID_PERSON_ADDRESS LONG NOT NULL,
    ID_CAR LONG NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON_PERSON_ADDRESS FOREIGN KEY (ID_PERSON_ADDRESS) REFERENCES PERSON_ADDRESS (ID),
    CONSTRAINT FK_PERSON_CAR FOREIGN KEY (ID_CAR) REFERENCES CAR (ID)
);

CREATE TABLE PET (
    ID LONG NOT NULL,
    NAME VARCHAR(20) NULL,
    ID_PERSON LONG NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PET_PERSON FOREIGN KEY (ID_PERSON) REFERENCES PERSON (ID)
);